---
apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-example
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailspin
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
  source:
    repoURL: https://github.com/lijcam/tailspin-monitor.git
    targetRevision: HEAD
    path: base
  destination:
    namespace: sidecar-example
    server: https://kubernetes.default.svc